name: CI for debug build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
        platform: [x64, arm64]

    runs-on: windows-latest
    
    env:
      Solution_Name: EnergyStar.sln
      Project_Name: EnergyStar

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.400

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore
        run: dotnet restore $env:Solution_Name

      - name: Build
        run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ESX_Debug_Build_for_${{ matrix.platform }}
          path: "D:\\a\\EnergyStarX\\EnergyStarX\\EnergyStar\\bin\\${{ matrix.platform }}"
            
